### ISSUE TITLE
Find benchmark given scheme code

### ISSUE THREAD

**Issue by arunisaac** [NayakwadiS/mftool#12]
Hi,

Is there a way to get the benchmark of a scheme given its scheme code? I am trying to compare the historical performance of several funds with that of their benchmarks, and it would be helpful to easily find their benchmarks.

Thanks for developing and maintaining mftool!

**Comment by NayakwadiS** [comment]
Mapping benchmark with scheme code is difficult, but benchmarks has been already added in all scheme performance methods. 
Thanks.

**Comment by arunisaac** [comment]
Ok, thanks.
