### ISSUE TITLE
KeyError: 'user_agent'

### ISSUE THREAD

**Issue by vkamlesh** [NayakwadiS/mftool#15]
Error:
  File "/Users/vkamlesh/src/finpy/list_key.py", line 7, in <module>
    mf = Mftool()
  File "/Users/vkamlesh/src/finpy/mftodef get_open_ended_solution_scheme_performance(self, as_json=False):
        """

Implementing functionality for Solution-oriented and Other category funds.

    def get_open_ended_solution_scheme_performance(self, as_json=False):
        """
        gets the daily performance of open ended Solution-Oriented schemes for all AMCs
        :return: json format
        :raises: HTTPError, URLError
        """
        get_open_ended_solution_scheme_url = self._get_open_ended_equity_scheme_url.replace('SEQ','SOLU')
        scheme_performance = {}
        for key in self._open_ended_solution_category.keys():
            scheme_performance_url = get_open_ended_solution_scheme_url.replace('CAT',self._open_ended_solution_category[key])
            scheme_performance[key] = self.get_daily_scheme_performance(scheme_performance_url, False)
        return self.render_response(scheme_performance,as_json)

    
    def get_open_ended_other_scheme_performance(self, as_json=False):
        """
        gets the daily performance of open ended index and FoF schemes for all AMCs
        :return: json format
        :raises: HTTPError, URLError
        """
        get_open_ended_other_scheme_url = self._get_open_ended_equity_scheme_url.replace('SEQ','OTH')
        scheme_performance = {}
        for key in self._open_ended_solution_category.keys():
            scheme_performance_url = get_open_ended_other_scheme_url.replace('CAT',self._open_ended_other_category[key])
            scheme_performance[key] = self.get_daily_scheme_performance(scheme_performance_url, False)
        return self.render_response(scheme_performance,as_json)

**Comment by NayakwadiS** [comment]
Kindly provide key-values for `self._open_ended_solution_category[key]`  and  `self._open_ended_other_category[key]`

**Comment by vkamlesh** [comment]
"open_ended_solution_category": {
		"Children's" : "SOLU_CH",
		"Retirement" : "SOLU_RET"

	},
	"open_ended_other_category": {
		"Index Funds/ETFs" : "OTH_INDEX",
		"FoFs(Oversease/Domestic)" : "OTH_FOF"

	},

**Comment by NayakwadiS** [comment]
added
