### ISSUE TITLE
remove ETF from get_open_ended_other_scheme_performance() and create separate function for ETF

### ISSUE THREAD

**Issue by vkamlesh** [NayakwadiS/mftool#17]
Can we move ETF into a different function? 
Problem Statement: In case if someone requires information such as NAV,1/3/5 years return for a direct option and ETF. It would require to dump all data and filter out (latest NAV- Regular','1-Year Return(%)- Regular','3-Year Return(%)- Regular','5-Year Return(%)- Regular). Due to filtration, ETF performance can't be capture.
[code snippet ](https://pastebin.com/embed_js/n2VREHtY) 

Attached excel file.
[Other_Fund_Direct_Performance.xlsx](https://github.com/NayakwadiS/mftool/files/6213455/Other_Fund_Direct_Performance.xlsx)

**Comment by NayakwadiS** [comment]
1. Logically ETF is part of Other schemes and you also suggested in #15 
2. Data Analysis and Visualization are the part of personal projects.
