### ISSUE TITLE
Add feature to use proxies

### ISSUE THREAD

**Issue by coder-daga** [NayakwadiS/mftool#2]
Hey, could you add in a feature to add a proxy dictionary to the requests. I am behind a firewall and need to pass all requests through a proxy for this to work.

**Comment by NayakwadiS** [comment]
Sure. Will try to add this feature in next release.

**Comment by NayakwadiS** [comment]
Done. Follow below steps to pass all requests through proxy -

m = Mftool()
proxies = {'http': 'http://user:pass@10.10.1.0:1080',
    'https': 'http://user:pass@10.10.1.0:1090',
}
m.set_proxy(proxies) 
m.get_scheme_historical_nav("abcde",as_json=True)
