### ISSUE TITLE
[Feature Request] helper functions to calculate risk ratios

### ISSUE THREAD

**Issue by shantanu-deshmukh** [NayakwadiS/mftool#22]
Hey, great work with the mftool lib. 

Not sure if this fits in the scope or goals of the library, but it would be great if we can add helper functions for calculating risk ratio like alpha, beta, Sharpie Ration, Sortino Ratio, etc. 

These can be generic functions that accept data for both the MF & returns against which the ratio is calculated.

This will be helpful for individuals or projects which use this library to analyze funds.

**Comment by NayakwadiS** [comment]
Thanks.
Pl provide standard formulas to calculate all these risk ratios
