### ISSUE TITLE
Equity scheme performance data not getting downloaded

### ISSUE THREAD

**Issue by mbafinance2020** [NayakwadiS/mftool#23]
Hi

Looks like the performance data code is not working. Can you please check at your end and let me know if you are able to download the performance data?

**Comment by NayakwadiS** [comment]
Hey, this is because of latest changes in requests lib [here](https://github.com/psf/requests/issues/5817)

**Comment by NayakwadiS** [comment]
Pl make a change as per latest commit [1903041](https://github.com/NayakwadiS/mftool/commit/1903041b3f9553437ec3a4ce810c1f2777c65304) in your lib

**Comment by anirudh-agarwalla** [comment]
Unable to download performance data.
