### ISSUE TITLE
Unable to fetch data from AMFI.

### ISSUE THREAD

**Issue by vkamlesh** [NayakwadiS/mftool#24]
For the last few weeks, I am unable to fetch data from AMFI. 

>>> from mftool import Mftool
>>> mf = Mftool()
>>> mf.get_open_ended_debt_scheme_performance()
{'Long Duration': [], 'Medium to Long Duration': [], 'Medium Duration': [], 'Short Duration': [], 'Low Duration': [], 'Ultra Short Duration': [], 'Liquid': [], 'Money Market': [], 'Overnight': [], 'Dynamic Bond': [], 'Corporate Bond': [], 'Credit Risk': [], 'Banking and PSU': [], 'Floater': [], 'FMP': [], 'Gilt': [], 'Gilt with 10 year constant duration': []}
>>> mf.get_open_ended_equity_scheme_performance()
{'Large Cap': [], 'Large & Mid Cap': [], 'Multi Cap': [], 'Mid Cap': [], 'Small Cap': [], 'Value': [], 'ELSS': [], 'Contra': [], 'Dividend Yield': [], 'Focused': []}
>>> mf.get_open_ended_hybrid_scheme_performance()
{'Aggressive Hybrid': [], 'Balanced Hybrid': [], 'Conservative Hybrid': [], 'Equity Savings': [], 'Arbitrage': [], 'Multi Asset Allocation': []}

**Comment by NayakwadiS** [comment]
#23

**Comment by anirudh-agarwalla** [comment]
**CODE:**
value = mf.get_open_ended_equity_scheme_performance(True)
print(value)

value = mf.get_open_ended_debt_scheme_performance(True)
print(value)

**Output**
{"Large Cap": [], "Large & Mid Cap": [], "Multi Cap": [], "Mid Cap": [], "Small Cap": [], "Value": [], "ELSS": [], "Contra": [], "Dividend Yield": [], "Focused": []}
{"Long Duration": [], "Medium to Long Duration": [], "Medium Duration": [], "Short Duration": [], "Low Duration": [], "Ultra Short Duration": [], "Liquid": [], "Money Market": [], "Overnight": [], "Dynamic Bond": [], "Corporate Bond": [], "Credit Risk": [], "Banking and PSU": [], "Floater": [], "FMP": [], "Gilt": [], "Gilt with 10 year constant duration": []}

Can someone help me why this is happening?
