### ISSUE TITLE
[Feature Request] helper functions to get expense ratio of a MF

### ISSUE THREAD

**Issue by harsh253** [NayakwadiS/mftool#31]
Hey, really liked the mf tool.

Is there a possibility of creating an api that returns the expense ratio of each mutual fund according to the scheme_code ?

**Comment by dev-000** [comment]
@NayakwadiS Played around with it for some time. Loved it. Great tool. I second @harsh253 for this feature. Does AMFI provide a list with Expense ratios?

**Comment by NayakwadiS** [comment]
#35 
use method `get_scheme_info` with new scheme codes [here ](https://github.com/NayakwadiS/Forecasting_Mutual_Funds/blob/master/codes.json) to get expense ratio as

```
>>> info = mf.get_scheme_info("scheme_code",as_json=False)
>>> info['annualReportExpenseRatio']
```

**Comment by dev-000** [comment]
I seem to have no attribute called `get_scheme_info`  Getting the following error when I try to execute `mf.get_scheme_info(...)`
`AttributeError: 'Mftool' object has no attribute 'get_scheme_info'` 
Am I missing something here?

**Comment by dev-000** [comment]
I was trying intially with `pip install mftool` It seems to be installing the older version
I checked out the latest v2.5(Name is mentioned as v2.2 though on releases) from Releases in Github repo. 
I pip uinstalled the older version
Then on the downloaded release folder ran `python setup.py install`
Still doesnt seem to install it properly. Not sure what I am doing wrong.
