### ISSUE TITLE
get_open_ended_equity_scheme_performance and similar functions aren't working

### ISSUE THREAD

**Issue by surajkaul** [NayakwadiS/mftool#39]
The return is an empty dictionary. Is there a new url we can point to instead of the value research one?

**Comment by NayakwadiS** [comment]
It should work only if you do some changes at your local

1. Uncomment this [line](https://github.com/NayakwadiS/mftool/blob/a007a7f8155c522e458414aeb659b70c236427c9/mftool.py#L394)
2. Comment this [line](https://github.com/NayakwadiS/mftool/blob/a007a7f8155c522e458414aeb659b70c236427c9/mftool.py#L395)

If this works properly kindly mention here... then changes will go live in next release.

**Comment by surajkaul** [comment]
still getting the same empty dictionary

**Comment by uditbatra** [comment]
Getting response as {"Large Cap": [], "Large & Mid Cap": [], "Multi Cap": [], "Mid Cap": [], "Small Cap": [], "Value": [], "ELSS": [], "Contra": [], "Dividend Yield": [], "Focused": []}.

Please fix
