### ISSUE TITLE
get_scheme_info is not working as expected.

### ISSUE THREAD

**Issue by abhinandanp1** [NayakwadiS/mftool#44]
I am trying to execute get_scheme_info() for "0P0000XVYC" but it is not working .
I am getting :
"Exception: yfinance failed to decrypt Yahoo data response"

what could be the cause?

Sample code for reference:
`mfToolObject = Mftool()
scheme_info = mfToolObject.get_scheme_info("0P0000XVYC")
print(scheme_info)`

**Comment by NayakwadiS** [comment]
Its working correctly... kindly update your python to 3.9

![image](https://github.com/NayakwadiS/mftool/assets/39816455/68dd43cb-c908-45f0-91a0-5327cc31531c)
