### ISSUE TITLE
getting import error due to relative import

### ISSUE THREAD

**Issue by gsrana1992** [NayakwadiS/mftool#56]
from .utils import Utilities, is_holiday, get_today, get_friday, render_response
ImportError: attempted relative import with no known parent package

I am getting ImportError as the utils.py module is being import using relative path.

**Comment by NayakwadiS** [comment]
Have you checked with lib version 2.7.1 or you just checked in your local repo?

**Comment by gsrana1992** [comment]
I checked it with the current master branch code but let me check it again and update here soon.

**Comment by gsrana1992** [comment]
> Have you checked with lib version 2.7.1 or you just checked in your local repo?

Yes, it failed for me with 2.7.1

**Comment by gsrana1992** [comment]
Yes, 2.7.1 is indeed working. Closing this issue.
