### ISSUE TITLE
Error while requesting for function get_scheme_info()

### ISSUE THREAD

**Issue by 12tilak34** [NayakwadiS/mftool#59]
while requesting for any code for getting scheme info i'm getting this error: " UnboundLocalError: cannot access local variable 'response' where it is not associated with a value " . I'm getting error for each and every scheme code 

code: 
from mftool import Mftool
mf = Mftool()
data = mf.get_scheme_info('110024')
print(data)

**Comment by NayakwadiS** [comment]
Only use valid codes for `get_scheme_info`

[documentation](https://mftool.readthedocs.io/en/latest/#to-get-scheme-info-with-sector-weight-holdings-etc)
