### ISSUE TITLE
AUM data

### ISSUE THREAD

**Issue by RM-95** [NayakwadiS/mftool#6]
Hi! Your library is fantastic and very useful. However, I'm unable to fetch AUM data for the mutual funds. Is there a remedy for this?

**Comment by NayakwadiS** [comment]
Do we have any source to get AUM ?

**Comment by RM-95** [comment]
yes, I've attached the link below
https://www.amfiindia.com/research-information/other-data/scheme-details

**Comment by NayakwadiS** [comment]
Done
