### ISSUE TITLE
get_open_ended_equity_scheme_performance and similar functions aren't working

### ISSUE THREAD

**Issue by uditbatra** [NayakwadiS/mftool#71]
The return is an empty dictionary.

Getting response as {"Large Cap": [], "Large & Mid Cap": [], "Multi Cap": [], "Mid Cap": [], "Small Cap": [], "Value": [], "ELSS": [], "Contra": [], "Dividend Yield": [], "Focused": []}.

Please help.

**Comment by NayakwadiS** [comment]
This varies from machine to machine.
Pl make changes as per #23 in your local installation

**Comment by uditbatra** [comment]
Thanks for the response, 
I am trying to install the library using the source ocd on mac. 

Getting below error, please suggest what I might have missed @NayakwadiS 
<img width="812" alt="Screenshot 2024-03-25 at 8 10 20 PM" src="https://github.com/NayakwadiS/mftool/assets/3806195/e40ce3b1-bdc7-46f4-8262-9b7d40e292c9">

Thank you in advance!
