### ISSUE TITLE
Feature request- get_scheme_historical_dividend()

### ISSUE THREAD

**Issue by agent-jay** [NayakwadiS/mftool#76]
To better compare performance between funds, it would be great to be able to pull dividend payments by date, the same way that get_scheme_historical_nav pulls daily NAV.  It can be used to compute annual dividend yields

The main challenge here is to find a reliable source of dividend data. Most websites (ET money, valueresearch, etc) simply report the nav returns. It's not clear if the dividend yields are included as part of this. Any clarification on this would help as well. 

Thanks

**Comment by NayakwadiS** [comment]
I have tried to get a reliable source for dividend data but unfortunately it's difficult and illegal to scrap data from the mentioned sites.
Now it seems we are not able to add this feature.
