### ISSUE TITLE
Addition of fund manager details

### ISSUE THREAD

**Issue by rohitsathish** [NayakwadiS/mftool#8]
The get scheme details functions works well and provides most of the necessary information.

But an important, detail, the fund manager name and tenure at the MF is missing.

Is there any way we can add these 2 data points?

It's a common data point on most websites - https://www.valueresearchonline.com/funds/14890/axis-banking-and-psu-debt-fund?utm_source=direct-click&utm_medium=funds&utm_term=&utm_content=Axis+Banking+%26+PSU+Debt+Reg&utm_campaign=vro-search#fund-manager

**Comment by NayakwadiS** [comment]
It is difficult to add fund manager details
